docRoot                 $VH_ROOT/html
enableGzip              1

# Map index files
index  {
  useServer             0
  indexFiles            index.php, index.html
}

# Enable .htaccess rewrite support (Laravel, WordPress, etc.)
rewrite  {
  enable                1
  autoLoadHtaccess      1
}

# Map PHP handling to OpenLiteSpeed PHP 8.5
scripthandler  {
  add                   lsapi:lsphp85 php
}

# Access Control
accessControl  {
  allow                 *
}
